### PR TITLE
API-7350 update from fortify scan may 2021

### PR DESCRIPTION
**Pull request by crolarlibertyva**
- Modifications in support of the findings that were valid
  - The remaining fortify findings are false positives
- Removed dead code
- Regarding the dockerfile removals
  - When finding out what was on 'common' that was used by the code it turned out the be just 1 module, backgroundServer.js, that was used by 'e2etests.js'
  - So all of common was removed.
  - and thus references in the dockerfile were removed

### CODE REVIEW

**Comment by dbrown-va** [comment]
Recommend explaining in the PR why the Dockerfile removals are possible.

**Review by lukemarkwordtlibertyits — APPROVED** [review]
LGTM

**Review by dbrown-va — APPROVED** [review]

**Comment by crolarlibertyva** [comment]
Related devops PR at https://github.com/department-of-veterans-affairs/terraform-aws-dvp-saml-proxy/pull/17

**Review by duganth-va — APPROVED** [review]
Looks good to me

**Review by dbrown-va — APPROVED** [review]
Confirmed common directory removal and carry forward of health check endpoint with direct curl.

**Pull request merged**
