### PR TITLE
API-8148 saml login refactor and  jest update

### PR DESCRIPTION
**Pull request by crolarlibertyva**
- unit test redone to accommodate jest 27..0.x
- refactored samlLogin

### CODE REVIEW

**Comment by lukemarkwordtlibertyits** [comment]
# Review Steps

- [ ] Run Regression Tests
- [ ] Ensure login to DSLogin directs to the right page.
- [ ] Ensure login to MyHealtheVet directs to the right page.
- [ ] Ensure login to ID.me directs to the right page.
- [ ] Did unit tests stay the same?
- [ ] If they didn't what was the reason for the change?
- [ ] Did code coverage increase?

**Comment by crolarlibertyva** [comment]
> 
>     * [ ]  Did unit tests stay the same?

- Tests were changed to deal with async with regards to  'expect' checks being called before the underlying code had finished executing
- mock is now used for external lib calls to samlp in wsfed-passport to enable an error path check.

>     * [ ]  If they didn't what was the reason for the change?
- see above
>     * [ ]  Did code coverage increase?
- 83 from 80

**Comment by crolarlibertyva** [comment]
Gonna iterate another further refactor. So this PR will go into draft.

**Comment by crolarlibertyva** [comment]
- UT items are covered in https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/pull/337

**Comment by crolarlibertyva** [comment]
This PR address the jest upgrade and UT items. https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/pull/340

**Pull request closed without merging**
